---

- name: A playbook to install and start chrony
  hosts: webservers

  tasks:
    - name: install chrony
      yum:
        name: chrony
        state: installed

    - name: start chronyd service
      service:
        name: chronyd
        state: started
        enabled: yes

...
